"""
REPORT DELIVERY ROUTER (Compliance Delivery Interface)
------------------------------------------------------
Purpose:
    Exposes API endpoints for retrieving compliance report metadata and 
    streaming physical DSAPT audit files over HTTP.

Functionality:
    - Queries the database session layer to list generated report logs.
    - Bridges the web request layer to the physical storage artifacts 
      produced by the underlying computer vision pipeline.
    - Delivers automated, secure file streams directly to integrated client apps.

Integration:
    Acts as the target endpoint interface for the mobile frontend application 
    to trigger local downloads of finalized compliance ledgers.
"""

import os
from fastapi import APIRouter, HTTPException, Depends
from fastapi.responses import FileResponse
from sqlmodel import Session, select

# These match your team's exact folder paths (app/db and app/models)
from app.db.session import get_session
from app.models.report import Report

router = APIRouter()

# The absolute path where your accessiscan-ai pipeline drops its completed files
AUDIT_RESULTS_DIR = os.path.abspath("runs/detect/audit_results")

@router.get("/")
def get_reports(session: Session = Depends(get_session)):
    """Fetches all report metadata records from the database ledger"""
    reports = session.exec(select(Report)).all()
    return reports

@router.get("/download/{report_id}")
def download_report_file(report_id: int, session: Session = Depends(get_session)):
    """
    Finds the report entry in the DB, verifies the physical JSON file exists, 
    and streams it directly to the mobile app user as a download.
    """
    # 1. Look up the report tracking metadata in the DB using its ID
    report = session.get(Report, report_id)
    if not report:
        raise HTTPException(status_code=404, detail="Report record not found in database.")
    
    # 2. Map the ID to the physical file name generated by your storage manager
    file_name = f"report_{report_id}.json"
    file_path = os.path.join(AUDIT_RESULTS_DIR, file_name)
    
    # 3. Check physical file existence on the disk
    if not os.path.exists(file_path):
        raise HTTPException(status_code=404, detail="Physical audit file is missing from the storage server.")
        
    # 4. Stream the file back securely over the network as an attachment download
    return FileResponse(
        path=file_path, 
        media_type="application/json", 
        filename=f"DSAPT_Compliance_Report_{report_id}.json"
    )
